### ISSUE TITLE
DDL script doubts

### ISSUE THREAD

**Issue by n4xo-dev** [Soft-Coders/ABD#26]
# Dudas sobre el script DDL para la entrega 1
> Según se resuelvan los temas se van marcando las casillas

- [x] Variables repetidas en:
    - [x] `transaccion` -> 171, 173
    
- [x] Uso de `NVARCHAR2` en vez de `VARCHAR2` en:
    - [x] `cuenta referencia` -> 67
        - `saldo              NUMBER(12,0) NOT NULL,  -- Se considera como saldo máximo el patrimonio de Elon Musk`
    - [x] `depositar_en` -> 77
        - `saldo         NUMBER(12,0) NOT NULL,       -- Se considera como saldo máximo el patrimonio de Elon Musk`
    - [x] `tarjetas` -> 150, 152
        - `numero            NUMBER(16,0) NOT NULL,`
        - `cvv               NUMBER(3,0) NOT NULL,`
    - [x] `transaccion` -> 165, 168
       - `cantidad            NUMBER(9,0),          -- Transacción permite máximo 999.999.999`
       - `comision            NUMBER(8,0),          -- Máxima comisión contemplada es de 10% sobre 999.999.999 -> 99.999.999`

**Comment by jesuscestino** [comment]
Las variables repetidas se deben al propio diseño por defecto de la base de datos proporcionada por los profesores. El hecho de que transacción esté relacionada dos veces con cuenta y con divisa provoca que se repitan las claves foráneas, pero cada una hace referencia a emisor y receptor respectivamente.

**Comment by jesuscestino** [comment]
Vamos a cambiar todos los NVARCHAR A -----> NUMBER (p,s) donde p es PRECISIÓN y s ESCALA.
-La precisión es la cantidad de números que almacena.
-La escala es la cantidad de números decimales que almacena.

Si definimos un NUMBER(6,2) un ejemplo de numero que podemos almacenar es 1234,56

-Como la mayoría de variables que usamos son números enteros vamos a definir la precisión acorde a la naturaleza del atributo y **la escala será 0.**
