### ISSUE TITLE
Excepción por comprobar si algo está null?

### ISSUE THREAD

**Issue by ghost** [Soft-Coders/ABD#30]
https://github.com/Soft-Coders/ABD/blob/85d9734ca802a5cec09cf9de0969d871ca54191a/PL%20SQL/PROCEDURE_BAJA_CLIENTE.pls#L17

El profesor nos dijo que esa parte se haría con la interfaz no?? Entiendo que no importa para nada tenerlo ahí, pero lo digo para hacer yo las mías o no :)

**Comment by ghost** [comment]
@martame18 @jesuscestino @iLopezosa

**Comment by n4xo-dev** [comment]
@pablohud  Este CLIENTE_ID es una variable donde se guardaría el ID del cliente en caso de existir. Pero se asume que el parámetro del ID que se le pasa a la función (P_IDENTIFIACIÓN) no es null. Es a esto último a lo que se refería el profe, no es necesario comprobar que los parámetros de entrada obligatorios sean null o no (excepto para discriminar entre diferentes tipos de tablas como hago yo con POOLED y SEGREGADA).
> DISCLAIMER: Al menos eso es lo que he entendido de revisar el código. @jesuscestino

**Comment by jesuscestino** [comment]
Habia un error fruto de haber cambiado el codigo, ya esta corregido.
Como dice Nacho, es para saber si el cliente existe, ya que asumimos que el parametro no es null.
